add 7 module tasks
js-tasks-ru/jsbasic-20231211_hearths-holier-0z pull request #8
Opened 2024-01-12 17:02 UTC by sofi-bel

2024-01-12 17:03 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2024-01-12 17:33 UTC, koalex requested changes
Исправить замечания **7-4**

2024-01-12 17:33 UTC, koalex commented on 7-module/4-task/index.js
> +    this.elem.addEventListener('pointerdown', this.onPointerDown);
`this.thumb.addEventListener('pointerdown', this.onPointerDown);`

2024-01-12 17:33 UTC, koalex commented on 7-module/4-task/index.js
> +    this.elem.addEventListener('pointermove', this.onPointerMove);
`document.addEventListener('pointermove', this.onPointerMove);`

2024-01-12 17:33 UTC, koalex commented on 7-module/4-task/index.js
> +        this.emitSliderChangeEvent();
Эту строку `this.emitSliderChangeEvent();` нужно перенести в метод `onPointerUp` т.к. событие должно быть когда отпускаем кнопку мыши. В этом методе её быть не должно.

2024-01-12 17:33 UTC, koalex commented on 7-module/4-task/index.js
> +
Вот сюда добавляем `this.emitSliderChangeEvent();`

2024-01-12 17:33 UTC, koalex commented on 7-module/4-task/index.js
> +    this.elem.removeEventListener('pointermove', this.onPointerMove);
`document.removeEventListener('pointermove', this.onPointerMove);`

2024-01-12 17:53 UTC, jsru commented
Добавляю преподавателя (@koalex) для код-ревью.

2024-01-13 05:27 UTC, koalex approved these changes

2024-01-13 05:27 UTC, merged